version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro
    ports:
      - '4000:4000'
    depends_on:
      - user-service
      - post-service
  client:
    build:
      context: ./client
      args:
        BUILD_ENV: development
    container_name: client
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres_post_dev
      - postgres_user_dev
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"

  postgres_post_dev:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpassword
      POSTGRES_DB: postdb
    volumes:
      - postgres_post_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  postgres_user_dev:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: userdb
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  user-service:
    container_name: user-service
    build:
      context: ./microservices/user-service
      args:
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/user-service:/app
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DATABASE_URL=postgres://useruser:userpassword@postgres_user_dev:5432/userdb
      - REDIS=redis://localhost:6379
      - RABBITMQ=amqp://localhost:5672
    depends_on:
      - postgres_user_dev
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"

  post-service:
    container_name: post-service
    build:
      context: ./microservices/post-service
      args:
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/post-service:/app
    ports:
      - 4002:4002
    environment:
      - NODE_ENV=development
      - PORT=4002
      - DATABASE_URL=postgres://postuser:postpassword@postgres_post_dev:5434/postdb
      - REDIS=redis://localhost:6379
      - RABBITMQ=amqp://localhost:5672
    depends_on:
      - postgres_post_dev
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - app_network

  rabbitmq:
    image: 'rabbitmq:management'
    image: 'rabbitmq:management'
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

volumes:
  postgres_post_data:
  postgres_user_data:
  redis_data:

networks:
  app_network:
    driver: bridge
