version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    depends_on:
      - user-service
      - post-service
      - auth-service
    networks:
      - app_network

  client:
    build:
      context: ./client
      args:
        BUILD_ENV: development
    container_name: client
    volumes:
      - ./client:/app
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - postgres_post
      - postgres_user
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

  postgres_post:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER_POST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_POST}
      POSTGRES_DB: ${POSTGRES_DB_POST}
    volumes:
      - postgres_post_data:/var/lib/postgresql/data
    container_name: postgres_post
    ports:
      - '${POSTGRES_POST_PORT}:${POSTGRES_DEFAULT_PORT}'
    networks:
      - app_network

  postgres_user:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USER}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    container_name: postgres_user
    networks:
      - app_network
    ports:
      - '${POSTGRES_USER_PORT}:${POSTGRES_DEFAULT_PORT}'

  postgres_auth:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_AUTH_PORT}:${POSTGRES_DEFAULT_PORT}'
    container_name: postgres_auth
    networks:
      - app_network

  auth-service:
    container_name: auth-service
    build:
      context: ./microservices/auth-service
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/auth-service:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${AUTH_SERVICE_PORT}
      - REDIS=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL_AUTH}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SECRET_KEY=${SECRET_KEY}
      - RABBITMQ_USER_EVENTS_QUEUE=${RABBITMQ_USER_EVENTS_QUEUE}
    depends_on:
      - postgres_auth
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

  user-service:
    container_name: user-service
    build:
      context: ./microservices/user-service
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/user-service:/app
      - ./microservices/user-service/uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${USER_SERVICE_PORT}
      - DATABASE_URL=${DATABASE_URL_USER}
      - REDIS=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_USER_EVENTS_QUEUE=${RABBITMQ_USER_EVENTS_QUEUE}
    depends_on:
      - postgres_user
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

  search-service:
    container_name: search-service
    build:
      context: ./microservices/search-service
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/search-service:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SEARCH_SERVICE_PORT}
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

  post-service:
    container_name: post-service
    build:
      context: ./microservices/post-service
      args:
        BUILD_ENV: development
    volumes:
      - ./microservices/post-service:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${POST_SERVICE_PORT}
      - DATABASE_URL=${DATABASE_URL_POST}
      - REDIS=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres_post
      - redis
      - rabbitmq
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - app_network

  rabbitmq:
    image: 'rabbitmq:management'
    container_name: rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

volumes:
  postgres_post_data:
  postgres_user_data:
  postgres_auth_data:
  redis_data:

networks:
  app_network:
    driver: bridge
