version: '3.8'

services:
  client:
    build:
      context: ./client
      args:
        BUILD_ENV: production
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
    depends_on:
      - user-service
      - post-service
    command: ["npm", "run", "preview"]  # Just run the preview after building

  user-service:
    build:
      context: ./microservices/user-service
      args:
        BUILD_ENV: production
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@user-db:5432/users_db
    command: ["npm", "start"]
    depends_on:
      - user-db

  post-service:
    build:
      context: ./microservices/post-service
      args:
        BUILD_ENV: production
    ports:
      - '5002:5002'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@post-db:5432/posts_db
    command: ["npm", "start"]
    depends_on:
      - post-db

  user-db:
    image: postgres:13
    container_name: postgres_user_prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - '5433:5432'

  post-db:
    image: postgres:13
    container_name: postgres_post_prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts_db
    ports:
      - '5434:5432'

networks:
  app_network:
    driver: bridge